# Site settings
title: "Josh O'Rourke"
description: "Co-founder of Saoirse Media and Escape Plan. Program Lead of Solution Architecture at King's Daughters Health System."
url: 'http://joshorourke.com'
baseurl: '/'
google_analytics: 'UA-41848585-6'
# disqus_shortname: 'your-disqus-name'

author:
  name: "Josh O'Rourke"
  email: josh.public@me.com
  github_username:  jpo
  linkedin_username:  joshorourke
  # facebook_username: joshgerdes
  # twitter_username: joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
